# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: build_linux
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - script: dotnet build
    displayName: dotnet build
    workingDirectory: pamela-soulis-project1

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'

- job: build_windows
  pool:
    vmImage: windows-latest

  steps:
  - task: VSBuild@1
    displayName: Visual Studio build
    inputs:
      solution: '**\*.sln'
      platform: 'Any CPU'
      configuration: 'Release'
      restoreNugetPackages: true
